export const REGISTER_KEY = {
	ENV_CONFIG: Symbol("ENV_CONFIG"),
	SESSION_STORE: Symbol("SESSION_STORE"),
	HEALTH_REPOSITORY: Symbol("HEALTH_REPOSITORY"),
	HEALTH_SERVICE: Symbol("HEALTH_SERVICE"),
} as const
