export const REGISTER_KEY = {
	ENV_CONFIG: Symbol("ENV_CONFIG"),
	SESSION_STORE: Symbol("SESSION_STORE"),
	AUTH_SERVICE: Symbol("AUTH_SERVICE"),
	HEALTH_REPOSITORY: Symbol("HEALTH_REPOSITORY"),
	HEALTH_SERVICE: Symbol("HEALTH_SERVICE"),
	SYSTEM_SETTINGS_REPOSITORY: Symbol("SYSTEM_SETTINGS_REPOSITORY"),
	SYSTEM_SETTINGS_SERVICE: Symbol("SYSTEM_SETTINGS_SERVICE"),
} as const
