import type { Metadata } from "next"
import { Geist, Geist_Mono, Noto_Sans } from "next/font/google"
import "./globals.css"

const notoSans = Noto_Sans({ variable: "--font-sans" })

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

import { TooltipProvider } from "src/shared/components/ui/tooltip"

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className={notoSans.variable}>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<TooltipProvider>{children}</TooltipProvider>
			</body>
		</html>
	)
}
